var a = 5;
var b = 2;
var isEqualTo = (a == b);
var isNotEqualTo = (a != b);
var isGreaterThan = (a > b);
var isSmallerThan = (a < b);
console.log(isEqualTo);
console.log(isNotEqualTo);
console.log(isGreaterThan);
console.log(isSmallerThan);
